### ISSUE TITLE
Sentinel-2/Creodias: band cols do not match

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#105]
Error occurs on creo after introducing a predefinedExtent to compute RasterRegion:
job-id: j-70f9222b84f24417a07b6f2d0e657cbf
LAEA20km tile: E452N392

```
java.lang.AssertionError: assertion failed: Band 3 cols does not match, 220 != 221
	at scala.Predef$.assert(Predef.scala:223)
	at geotrellis.raster.ArrayMultibandTile.(ArrayMultibandTile.scala:101)
	at geotrellis.raster.ArrayMultibandTile$.apply(ArrayMultibandTile.scala:46)
	at geotrellis.raster.MultibandTile$.apply(MultibandTile.scala:37)
	at org.openeo.geotrellis.layers.BandCompositeRasterSource.read(FileLayerProvider.scala:89)
	at geotrellis.raster.RasterSource.read(RasterSource.scala:128)
	at geotrellis.raster.RasterRegion$GridBoundsRasterRegion.$anonfun$raster$1(RasterRegion.scala:44)
	at scala.Option.flatMap(Option.scala:271)
	at geotrellis.raster.RasterRegion$GridBoundsRasterRegion.raster$lzycompute(RasterRegion.scala:43)
	at geotrellis.raster.RasterRegion$GridBoundsRasterRegion.raster(RasterRegion.scala:41)
	at org.openeo.geotrellis.layers.FileLayerProvider$$anon$3.loadData(FileLayerProvider.scala:466)
	at org.openeo.geotrelliscommon.SCLConvolutionFilterStrategy.loadMasked(CloudFilterStrategy.scala:173)
	at org.openeo.geotrellis.layers.FileLayerProvider$.$anonfun$loadPartition$6(FileLayerProvider.scala:435)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)

```

**Comment by jdries** [comment]
This band is likely to be the first 20m band. Gridbounds of 220 is weird because we work with chunks of 1024, but maybe on the edge?

**Comment by jdries** [comment]
Apparently, reading from rastersrouce with gridbounds can indeed return a smaller extent than the one requested.
Composite raster source thus has to deal with this.
