### ISSUE TITLE
Error: LINEARRING EMPTY when requesting data from SentinelHub

### ISSUE THREAD

**Issue by JanssenBrm** [Open-EO/openeo-geotrellis-extensions#128]
## Description

In one of our processes, we are fetching data from SentinelHub. However, we see something strange in this data retrieval step. When we request the data for a specific polygon in 2017, everything is working fine. When we request data for the same polygon in 2018, we get the following error message:
 
`Internal: Server error: Cannot create a polygon with exterior with fewer than 4 points: LINEARRING EMPTY (ref: r-02c11b2ef77243d98e9a09a5c2007aa4)`

Does anybody have an idea what could be causing this behavior? 
 
Some information to reproduce the issue:

## Python Sample
```python
dc = conn \
        .load_collection('SENTINEL2_L2A_SENTINELHUB',
                         bands=["B03", "B04", "B08", "sunAzimuthAngles", "sunZenithAngles", "viewAzimuthMean",
                                "viewZenithMean", 'SCL']) \
        .filter_spatial(features) \
        .filter_temporal(date_range)
```

## Processing Graph
```json
"loadcollection1": {
        "process_id": "load_collection",
        "arguments": {
            "bands": [
                "B03",
                "B04",
                "B08",
                "sunAzimuthAngles",
                "sunZenithAngles",
                "viewAzimuthMean",
                "viewZenithMean",
                "SCL"
            ],
            "id": "SENTINEL2_L2A_SENTINELHUB",
            "spatial_extent": null,
            "temporal_extent": null
        }
    },
    "filterspatial1": {
        "process_id": "filter_spatial",
        "arguments": {
            "data": {
                "from_node": "loadcollection1"
            },
            "geometries": {
                "type": "FeatureCollection",
                "features": [
                    {
                        "type": "Feature",
                        "properties": {
                            "id": 1
                        },
                        "geometry": {
                            "type": "Polygon",
                            "coordinates": [
                                [
                                    [
                                        -0.20057735970203852,
                                        53.24811471153172
                                    ],
                                    [
                                        -0.19884885496214083,
                                        53.24840102826777
                                    ],
                                    [
                                        -0.19791567448906724,
                                        53.24635439382115
                                    ],
                                    [
                                        -0.19964948139074376,
                                        53.246089285732204
                                    ],
                                    [
                                        -0.20057735970203852,
                                        53.24811471153172
                                    ]
                                ]
                            ]
                        }
                    }
                ]
            }
        }
    },
    "filtertemporal1": {
        "process_id": "filter_temporal",
        "arguments": {
            "data": {
                "from_node": "filterspatial1"
            },
            "extent": [
                "2018-01-01",
                "2018-12-31"
            ]
        },
        "result": true
    }
}
```

**Comment by JanssenBrm** [comment]
Related logs, as found by @jdries:

```
.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 401004.0 failed 4 times, most recent failure: Lost task 3.3 in stage 401004.0 (TID 71300994) (epod051.vgt.vito.be executor 3006): java.lang.RuntimeException: Cannot create a polygon with exterior with fewer than 4 points: LINEARRING EMPTY at scala.sys.package$.error(package.scala:30) at 
geotrellis.vector.PolygonConstructors.apply(Polygon.scala:62) at 
geotrellis.vector.PolygonConstructors.apply$(Polygon.scala:56) at 
geotrellis.vector.Polygon$.apply(Polygon.scala:87) at 
geotrellis.vector.PolygonConstructors.apply(Polygon.scala:45) at 
geotrellis.vector.PolygonConstructors.apply$(Polygon.scala:44) at 
geotrellis.vector.Polygon$.apply(Polygon.scala:87) at 
org.openeo.geotrellissentinelhub.package$.$anonfun$polygonExteriors$2(package.scala:145) at 
scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238) at 
scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36) at 
scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33) at 
scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198) at 
scala.collection.TraversableLike.map(TraversableLike.scala:238) at 
scala.collection.TraversableLike.map$(TraversableLike.scala:231) at 
scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198) at 
org.openeo.geotrellissentinelhub.package$.$anonfun$polygonExteriors$1(package.scala:144) at 
org.openeo.geotrellissentinelhub.package$.$anonfun$polygonExteriors$1$adapted(package.scala:143) at 
scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245) at 
scala.collection.immutable.List.foreach(List.scala:392) at 
scala.collection.TraversableLike.flatMap(TraversableLike.scala:245) at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242) at 
scala.collection.immutable.List.flatMap(List.scala:355) at 
org.openeo.geotrellissentinelhub.package$.polygonExteriors(package.scala:143) at 
org.openeo.geotrellissentinelhub.package$.simplify(package.scala:151) at 
org.openeo.geotrellissentinelhub.PyramidFactory.$anonfun$datacube_seq$15(PyramidFactory.scala:352)
```

**Comment by gutkinn** [comment]
Another related issue, same one I guess but good to have another reference: Internal: Server error: Cannot create a polygon with exterior with fewer than 4 points: LINEARRING EMPTY (ref: r-b19cd819ca114d10bcf8783c798b1bea)

**Comment by gutkinn** [comment]
It doesn't seem to have anything to do with the Polygons themselves: I created an entirely different polygon over the same area in QGIS and still getting this error. @JanssenBrm maybe something to do with the pockets of data unavailability for Sentinel from some years?

**Comment by bossie** [comment]
Narrowed the problem down to a single date (2018-10-07) for the original request, makes debugging easier:

```json
{
    "process": {
        "process_graph": {
            "loadcollection1": {
                "process_id": "load_collection",
                "arguments": {
                    "bands": [
                        "B03",
                        "B04",
                        "B08",
                        "sunAzimuthAngles",
                        "sunZenithAngles",
                        "viewAzimuthMean",
                        "viewZenithMean",
                        "SCL"
                    ],
                    "id": "SENTINEL2_L2A_SENTINELHUB",
                    "spatial_extent": null,
                    "temporal_extent": null
                }
            },
            "filterspatial1": {
                "process_id": "filter_spatial",
                "arguments": {
                    "data": {
                        "from_node": "loadcollection1"
                    },
                    "geometries": {
                        "type": "FeatureCollection",
                        "features": [
                            {
                                "type": "Feature",
                                "properties": {
                                    "id": 1
                                },
                                "geometry": {
                                    "type": "Polygon",
                                    "coordinates": [
                                        [
                                            [
                                                -0.20057735970203852,
                                                53.24811471153172
                                            ],
                                            [
                                                -0.19884885496214083,
                                                53.24840102826777
                                            ],
                                            [
                                                -0.19791567448906724,
                                                53.24635439382115
                                            ],
                                            [
                                                -0.19964948139074376,
                                                53.246089285732204
                                            ],
                                            [
                                                -0.20057735970203852,
                                                53.24811471153172
                                            ]
                                        ]
                                    ]
                                }
                            }
                        ]
                    }
                }
            },
            "filtertemporal1": {
                "process_id": "filter_temporal",
                "arguments": {
                    "data": {
                        "from_node": "filterspatial1"
                    },
                    "extent": [
                        "2018-10-07",
                        "2018-10-07"
                    ]
                },
                "result": true
            }
        }
    }
}

```
