### ISSUE TITLE
colormap error

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#138]
We still have an error related to serialization of the geotiff colormap:

  ```
  from matplotlib.colors import ListedColormap
    col_palette = [
        [174, 199, 232, 255],  
        [214, 39, 40, 255],  
        [247, 182, 210, 255],  
        [219, 219, 141, 255],  
        [199, 199, 199, 255]

    ]
    cmap = ListedColormap(col_palette)
    classification_colors = {x: [c / 255.0 for c in cmap(x)] for x in range(0, len(col_palette))}
    return classification_colors
```

```


Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2672)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2608)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2607)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2607)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1182)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1182)
        at scala.Option.foreach(Option.scala:407)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1182)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2860)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2802)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2791)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:952)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2228)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2249)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2268)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2293)
        at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1021)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:406)
        at org.apache.spark.rdd.RDD.collect(RDD.scala:1020)
        at org.openeo.geotrellis.geotiff.package$.saveRDDTemporal(package.scala:129)
        at org.openeo.geotrellis.geotiff.package.saveRDDTemporal(package.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassCastException: cannot assign instance of spire.std.DoubleAlgebra to field geotrellis.raster.render.BreakMap.evidence$1 of type org.locationtech.geopyspark.shaded.cats.kernel.Order in instance of geotrellis.raster.render.BreakMap$mcDI$sp
        at java.base/java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2205)
        at java.base/java.io.ObjectStreamClass$FieldReflector.checkObjectFieldValueTypes(ObjectStreamClass.java:2168)
        at java.base/java.io.ObjectStreamClass.checkObjFieldValueTypes(ObjectStreamClass.java:1422)
        at java.base/java.io.ObjectInputStream.defaultCheckFieldValues(ObjectInputStream.java:2506)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2413)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2490)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2384)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2490)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2384)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2490)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2384)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681)
        at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2128)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2490)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2384)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681)
        at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2128)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2490)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2384)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2490)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2384)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681)
        at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2490)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2384)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2222)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1681)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
        at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:85)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:136)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ... 1 more

```

**Comment by EmileSonneveld** [comment]
In the breakMap object there are some evidence parameters that cause an issue.
They get created somewhere here: https://github.com/locationtech-labs/geopyspark/blob/master/geopyspark/geotrellis/color.py#L174-L176

![image](https://user-images.githubusercontent.com/2298426/228588965-726ebcfe-8d30-4339-8896-944d379b70ad.png)

Maybe this can be fixed by using the same kind of hack as here: https://github.com/Open-EO/openeo-geotrellis-extensions/issues/108

**Comment by EmileSonneveld** [comment]
This snippet will run correctly when launched from Scala, but will throw when launched from Python:
```scala
  def test(sc: SparkContext): Unit = {
    //    val sc = SparkContext.getOrCreate
    val mCopy = "0.0:aec7e8ff;1.0:d62728ff;2.0:f7b6d2ff;3.0:dbdb8dff;4.0:c7c7c7ff".split(";").map(x => {
      val l = x.split(":");
      // parseUnsignedInt, because there is no minus sign in the hexadecimal representation.
      // When casting an unsigned int to an int, it will correctly overflow
      Tuple2(l(0).toDouble, Integer.parseUnsignedInt(l(1), 16))
    }).toMap
    val colorMap = new DoubleColorMap(mCopy)
    val formatOptions = new GTiffOptions()
    formatOptions.setColorMap(colorMap)


    val spire = new DoubleAlgebra()

    val data = sc.parallelize(Seq(1, 2, 3))
    val result = data.map(x => {
      println(spire)
      println(formatOptions)
      x
    })
    result.collect()
    print("test done")
  }
```
I guess this is because of different objects/libraries available in the runtime environment, messing with the serialising process

To run from python:
```Python
        from openeogeotrellis.utils import get_jvm
        sc = get_jvm().org.apache.spark.SparkContext.getOrCreate()
        get_jvm().org.openeo.geotrellis.geotiff.package.test(sc)
```

**Comment by jdries** [comment]
Aha, so this type: type org.locationtech.geopyspark.shaded.cats.kernel.Order seems wrong, because when I look in the code, it should be of type spire.algebra.Order
But we also see that some 'shading' has happened, where this 'cats.kernel.Order' type got relocated to a different package. It's quite likely that this causes some kind of mixup.

**Comment by jdries** [comment]
Note that nowadays, spark has a dependency on cats-kernel_2.12-2.1.1
Perhaps we can remove this shading rule from pom.xml and it might work?

<relocation>
    
    <pattern>cats.kernel</pattern>
    <shadedPattern>org.locationtech.geopyspark.shaded.cats.kernel</shadedPattern>
</relocation>

**Comment by EmileSonneveld** [comment]
Commenting out the `cats.kernel org.locationtech.geopyspark.shaded.cats.kernel` part from pom.xml changes the namespace of `Order`:

`Caused by: java.lang.ClassCastException: cannot assign instance of spire.std.DoubleAlgebra to field geotrellis.raster.render.BreakMap.evidence$1 of type spire.algebra.Order in instance of geotrellis.raster.render.BreakMap$mcDI$sp`

**Comment by jdries** [comment]
I now removed geotrellis entirely from assembly jar:
https://artifactory.vgt.vito.be/webapp/#/artifacts/browse/tree/General/auxdata-public/openeo/geotrellis-backend-assembly-0.4.8-openeo_2.12.jar
Can you try if that works/helps?

**Comment by EmileSonneveld** [comment]
It still gives: `ClassCastException: cannot assign instance of spire.std.DoubleAlgebra to field geotrellis.raster.render.BreakMap.evidence$1 of type org.locationtech.geopyspark.shaded.cats.kernel.Order in instance of geotrellis.raster.render.BreakMap$mcDI$sp`
I comitted the scala test function on develop, for easier debugging: https://github.com/Open-EO/openeo-geotrellis-extensions/commit/eac875794ce143cd13cbb5569730e43c4f612e79

**Comment by jdries** [comment]
need to retry running test from python, assembly jar got removed

**Comment by EmileSonneveld** [comment]
I tried running the snippet again from python, but got the same error.
https://github.com/Open-EO/openeo-geotrellis-extensions/blob/develop/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/geotiff/package.scala#L739

The scala code seems still to refer to geotrelis code in a jar: `/home/emile/.m2/repository/org/locationtech/geotrellis/geotrellis-raster_2.12/3.6.0/geotrellis-raster_2.12-3.6.0-sources.jar!/geotrellis/raster/render/ColorMap.scala`

**Comment by JeroenVerstraelen** [comment]
Provide more information about job_option to @VictorVerhaert

**Comment by JeroenVerstraelen** [comment]
There is a difference between colormaps with doubles or integers. So one might work while the other doesn't. Check with @VictorVerhaert

**Comment by EmileSonneveld** [comment]
@VictorVerhaert Can you attach a job-id that failed?

**Comment by EmileSonneveld** [comment]
This setting worked:
```python
datacube = connection.load_collection(
    "SENTINEL2_L2A",
    spatial_extent={"east": 4.5, "north": 50.9, "south": 50.7, "west": 4.2},
    temporal_extent=["2023-06-01", "2023-06-01"],
    bands=["SCL"],
)
colormap = {
    0: [0, 0, 0],
    1: [255, 34, 30],
    2: [66, 66, 66],
    3: [133, 65, 29],
    4: [0, 255, 73],
    5: [250, 255, 78],
    6: [46, 00, 196],
    7: [117, 113, 113],
    8: [173, 169, 169],
    9: [207, 205, 205],
    10: [00, 199, 251],
    11: [255, 93, 248],
}
colormap = {k: [v / 255 for v in value] + [1] for k, value in colormap.items()}
datacube = datacube.save_result(format="GTiff", options={"colormap": colormap})
```

<img width="782" height="499" alt="Image" src="https://github.com/user-attachments/assets/73f4740f-7a0f-44f5-b7d8-b2180e929e48" />

<img width="316" height="428" alt="Image" src="https://github.com/user-attachments/assets/5f062fd0-0a3f-4098-b91d-383b81672c97" />

**Comment by EmileSonneveld** [comment]
GISAT confirms this works. Just need to double check if the documentation is fine. It should for example be documented with the format options

**Comment by EmileSonneveld** [comment]
This would be a nice place to add, but probably colormap is not in the general OpenEO spec. https://github.com/Open-EO/openeo-processes/blob/master/meta/subtype-schemas.json#L241

<details>
  <summary>JSON schema draft</summary>
  
  ```json
            "properties": {
                "colormap": {
                    "description": "Color map dictionary to be applied when exporting raster data.",
                    "type": "object",
                    "additionalProperties": {
                        "anyOf": [
                            {
                                "type": "integer"
                            },
                            {
                                "type": "array",
                                "items": {
                                    "type": "number",
                                    "minimum": 0,
                                    "maximum": 1
                                },
                                "minItems": 4,
                                "maxItems": 4
                            }
                        ]
                    }
                }
            }
  ```
</details>


@jdries Would a page in the cookbook be better? https://open-eo.github.io/openeo-python-client/cookbook/

**Comment by jdries** [comment]
@EmileSonneveld  This is where this option is documented, which requires improving:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/7a3077661e714167b51432aabbaf5f38fb4e26da/openeogeotrellis/backend.py#L495
I believe that you are allowed to also use more complex schemas, just like in process definitions. That would help tools like the web editor.

**Comment by EmileSonneveld** [comment]
New menu guides guides you to create a colormap. For example:
<img width="1179" height="728" alt="Image" src="https://github.com/user-attachments/assets/5c9d6467-9a44-49ed-8c09-a46806c68864" />

**Comment by VictorVerhaert** [comment]
"specified by an integer" -> This turned out incorrect right? 
I thought the keys needs to be mapped to an array of floats?

**Comment by EmileSonneveld** [comment]
You can use integer and/or an array of numbers. This would give you the same results:
```python
colormap = {
    0.0: 255,
    1.0: 4280426239,
    2.0: 1111638783,
    3.0: 2235637247,
    4.0: 16730623,
    5.0: 4211035903,
    6.0: 771802367,
    7.0: 1970369023,
    8.0: 2913577471,
    9.0: 3486371327,
    10.0: 13106175,
    11.0: 4284348671,
}
datacube = datacube.save_result(format="GTiff", options={"colormap": colormap})
```

**Comment by EmileSonneveld** [comment]
@jdries Does the documentation of the properties look good a few comments back? https://github.com/Open-EO/openeo-geotrellis-extensions/issues/138#issuecomment-3236495089 
I would have liked to give an explicit example, but the schema looks a bit tight to add it

**Comment by jdries** [comment]
the description can be markdown, perhaps we can use that to provide a properly formatted example?

**Comment by EmileSonneveld** [comment]
Markdown indeed does work. IT does not have Python highlighting, the description is shown twice, and there is a lot of empty space around the properties, but those are editor issues.
<img width="1293" height="816" alt="Image" src="https://github.com/user-attachments/assets/c4318d92-425a-4c6d-8eea-a2cd7393a8d5" />

**Comment by VictorVerhaert** [comment]
"specified by an integer" should still be changed to something like "specified by an integer or an rgba array of floats" right?
