### ISSUE TITLE
upgrade to Spark 3.4

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geotrellis-extensions#147]
https://github.com/Open-EO/openeo-geopyspark-driver/issues/281 has some issues with Spark accumulators in combination with speculative execution that Spark 3.4 should improve.

Upgrade to Spark 3.3 happened in #109 so look there for an upgrade procedure.

**Comment by bossie** [comment]
As discussed, to speed things up we assume that Spark 3.4.0 is fully backwards compatible and only upgrade the Spark that is actually part of the Docker image.

**Comment by bossie** [comment]
Built a new `spark-bin-3.4.0` RPM.

**Comment by bossie** [comment]
Web app Spark on Terrascope is 3.4.0 but I broke batch job submission:

> /opt/venv/lib64/python3.8/site-packages/openeogeotrellis/deploy/submit_batch_job_spark3.sh: line 107: spark-submit: command not found

**Comment by bossie** [comment]
[This fix](https://issues.apache.org/jira/browse/SPARK-33782) in Spark 3.4.0 probably broke the k8s driver:

```
Files  local:///opt/layercatalog.json from /opt/layercatalog.json to /opt/./layercatalog.json
{"name":"org.apache.spark.network.util.JavaUtils","levelname":"WARNING","message":"Attempt to delete using native Unix OS command failed for path = /opt/./layercatalog.json. Falling back to Java IO way","created":1682596337.287720000,"filename":"JavaUtils.java","lineno":116,"exc_info":"java.io.IOException: Failed to delete: /opt/./layercatalog.json\n\tat org.apache.spark.network.util.JavaUtils.deleteRecursivelyUsingUnixNative(JavaUtils.java:177)\n\tat org.apache.spark.network.util.JavaUtils.deleteRecursively(JavaUtils.java:113)\n\tat org.apache.spark.network.util.JavaUtils.deleteRecursively(JavaUtils.java:94)\n\tat org.apache.spark.util.Utils$.deleteRecursively(Utils.scala:1231)\n\tat org.apache.spark.deploy.SparkSubmit.$anonfun$prepareSubmitEnvironment$14(SparkSubmit.scala:433)\n\tat scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)\n\tat scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)\n\tat scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)\n\tat scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)\n\tat scala.collection.TraversableLike.map(TraversableLike.scala:286)\n\tat scala.collection.TraversableLike.map$(TraversableLike.scala:279)\n\tat scala.collection.AbstractTraversable.map(Traversable.scala:108)\n\tat org.apache.spark.deploy.SparkSubmit.downloadResourcesToCurrentDirectory$1(SparkSubmit.scala:424)\n\tat org.apache.spark.deploy.SparkSubmit.$anonfun$prepareSubmitEnvironment$16(SparkSubmit.scala:446)\n\tat scala.Option.map(Option.scala:230)\n\tat org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:446)\n\tat org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)\n\tat org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:192)\n\tat org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:215)\n\tat org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)\n\tat org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)\n\tat org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)\n\tat org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)\n"}
Exception in thread "main" java.io.IOException: Failed to delete: /opt/./layercatalog.json
	at org.apache.spark.network.util.JavaUtils.deleteRecursivelyUsingJavaIO(JavaUtils.java:150)
	at org.apache.spark.network.util.JavaUtils.deleteRecursively(JavaUtils.java:121)
	at org.apache.spark.network.util.JavaUtils.deleteRecursively(JavaUtils.java:94)
	at org.apache.spark.util.Utils$.deleteRecursively(Utils.scala:1231)
	at org.apache.spark.deploy.SparkSubmit.$anonfun$prepareSubmitEnvironment$14(SparkSubmit.scala:433)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.deploy.SparkSubmit.downloadResourcesToCurrentDirectory$1(SparkSubmit.scala:424)
	at org.apache.spark.deploy.SparkSubmit.$anonfun$prepareSubmitEnvironment$16(SparkSubmit.scala:446)
	at scala.Option.map(Option.scala:230)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:446)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:192)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:215)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by bossie** [comment]
OK on Terrascope, k8s TBC.

**Comment by jdries** [comment]
done on CDSE as well
