### ISSUE TITLE
proba-v-mep.esa.int are getting removed. This causes errors in geotrellis-seeder

### ISSUE THREAD

**Issue by EmileSonneveld** [Open-EO/openeo-geotrellis-extensions#176]
Error: https://jenkins.vgt.vito.be/job/openEO/job/openeo-geotrellis-extensions/job/develop/570/testReport/(root)/ReferenceTileTest/testSaveAndCompareAll/

Probably requests can be changed to https://services.terrascope.be/catalogue

**Comment by EmileSonneveld** [comment]
The error on Jenkins is:

`ReferenceTileTest.testSaveAndCompareAll`

```
com.sun.jersey.api.client.UniformInterfaceException: GET https://proba-v-mep.esa.int/api/catalog/v2/CGS_S2_FAPAR?startDate=2019-03-03&endDate=2019-03-03&format=GEOTIFF returned a response status of 500 Internal Server Error
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:688)
	at com.sun.jersey.api.client.WebResource.access$300(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:508)
	at be.vito.eodata.catalog.CatalogClient.getProducts(CatalogClient.java:148)
	at org.openeo.geotrellisseeder.TileSeeder.renderPng(TileSeeder.scala:106)
	at org.openeo.geotrellisseeder.TileSeeder.renderSinglePng(TileSeeder.scala:51)
```

**Comment by EmileSonneveld** [comment]
Seeding is not moved often anymore. Maybe some tests may be removed.

**Comment by dsamaey** [comment]
Test is already removed
