### ISSUE TITLE
Error in test_multiple_months

### ISSUE THREAD

**Issue by EmileSonneveld** [Open-EO/openeo-geotrellis-extensions#212]
Running this test has an error at one of the later nodes: https://github.com/jdries/worldwater-toolbox/blob/vito/tests/test_openeo_integration.py#L54
![image](https://github.com/Open-EO/openeo-geotrellis-extensions/assets/2298426/d54660c3-215f-4836-9ae2-cf89c8d634a0)

`j-1f6a4ab50afa46ec9a6f6d35527a9c81`

**Comment by EmileSonneveld** [comment]
The error message:

```
Lost task 16.0 in stage 92.0 (TID 1584) (10.42.212.180 executor 19): java.lang.AssertionError: assertion failed: Band count must be greater than 0 
at scala.Predef$.assert(Predef.scala:223)
at geotrellis.raster.ArrayMultibandTile.<init>(ArrayMultibandTile.scala:91)
```

**Comment by dsamaey** [comment]
Is this still an issue ?  Can we still run this test ?

**Comment by jdries** [comment]
Yes, we can and should run it.
