### ISSUE TITLE
raster_to_vector process causes Stackoverflow

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geotrellis-extensions#312]
The raster_to_vector process causes a stackoverflow error on the executors when processing the collect() call [at the following line](https://github.com/Open-EO/openeo-geotrellis-extensions/blob/develop/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/OpenEOProcesses.scala#L556):
```
    val collectedFeatures: Array[(String, List[PolygonFeature[Map[String, Int]]])] = vectorizedValuesWithMap.map(kv => {
      val key: K = kv._1
      val value: List[PolygonFeature[Map[String, Int]]] = kv._2
      val bandStr = "band0"
      key match {
        case stk: SpaceTimeKey =>
          val id = bandStr + "_" + stk.time.format(DateTimeFormatter.ofPattern("yyyyMMdd"))
          (id, value)
        case _ =>
          (bandStr, value)
      }
    }).collect()
```

This causes the vectorization process in the [parcel delination notebook](https://github.com/Open-EO/openeo-community-examples/blob/main/python/ParcelDelineation) to fail:
j-240731df876f46188b3737ed69e4b582

```
java.lang.StackOverflowError
at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:488)
at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:97)
at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:540)
at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:645)
at com.twitter.chill.TraversableSerializer.$anonfun$write$1(Traversable.scala:29)
at com.twitter.chill.TraversableSerializer.$anonfun$write$1$adapted(Traversable.scala:27)
at scala.collection.immutable.Map$Map1.foreach(Map.scala:193)
at com.twitter.chill.TraversableSerializer.write(Traversable.scala:27)
at com.twitter.chill.TraversableSerializer.write(Traversable.scala:21)
at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:79)
at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:508)
at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:575)
...
```

**Comment by JeroenVerstraelen** [comment]
Tested the following pg and the issue is still there at this moment:
https://gist.github.com/JeroenVerstraelen/05ac86b4f98babf90e6bcbc2a3133442

j-2504181647054bcc8e59e9030022fb6a

**Comment by JeroenVerstraelen** [comment]
It also started happening in our integrationtests (likely after the input data was reprocessed)

[raster_to_vector.json](https://gist.github.com/JeroenVerstraelen/4c5039a1df7b406b82c737aecf53b9ad)
![Image](https://github.com/user-attachments/assets/a8862c4a-e862-4a07-8bb0-2a58a05e5bbd)

[internal discussion](https://teams.microsoft.com/l/message/19:c462a30b534647ef86cf90b6581f6820@thread.tacv2/1750316633103?tenantId=9e2777ed-8237-4ab9-9278-2c144d6f6da3&groupId=befdddf8-55e8-4c70-855e-8802739f2ae9&parentMessageId=1750316633103&teamName=Remote%20Sensing%20Services&channelName=openeo-devs&createdTime=1750316633103)

**Comment by JeroenVerstraelen** [comment]
TODO: move integrationtest to a proper unit test that finds the root of this overflow issue.

**Comment by jdries** [comment]
I was able to reproduce in a unit test.
Somehow the serialization of a long list of specific type resulted in a long stack.  Changing to different type seems to fix things, will prepare PR.
For reference, it happens in this specific stage:
https://github.com/Open-EO/openeo-geotrellis-extensions/blob/d54c5cbb8c33ca90ed5f7ae1b923b871284d59f5/openeo-geotrellis/src/main/scala/org/openeo/geotrellis/OpenEOProcesses.scala#L683

**Comment by jdries** [comment]
Full AI explanation of the issue, which seems correct:

## The "Why": Recursive Cons Cells

In Scala, a List is a linked list composed of :: (Cons) cells. Each cell contains two fields: head (the value) and tail (a reference to the rest of the list).

When Kryo encounters a List, it doesn't always treat it as a "flat" collection. Depending on how it’s registered (or if it's using the default FieldSerializer), it sees the List as a nested object:

    Serialize the first :: cell.

    To do that, it must serialize the tail field.

    The tail is another :: cell.

    Kryo calls writeObject recursively for the tail.

## The Result: If you have a list of 10,000 elements, Kryo creates a call stack 10,000 frames deep. Most JVMs default to a stack size that blows up long before then.
Evidence in the Source Code
1. Kryo’s FieldSerializer

If Kryo hasn't been specifically told to use a CollectionSerializer for a specific Scala class, it defaults to FieldSerializer. In the Kryo source:
Java

// Simplified logic from FieldSerializer.java
public void write (Kryo kryo, Output output, T object) {
    for (Field field : fields) {
        // This call is the recursive step
        kryo.writeObject(output, field.get(object), serializer);
    }
}

Because the tail is a field of the same type, kryo.writeObject is called repeatedly until it hits Nil.
2. The chill Library

Spark uses a library called Twitter Chill to handle Scala-specific Kryo serializers. While Chill provides a ScalaCollectionsSerializer, the way Scala's List (and specifically the :: subclass) is handled can sometimes bypass iterative logic and fall back to recursion if the registration is inconsistent or if you're using a version where the "tail-recursive" serialization isn't optimized.
