### ISSUE TITLE
429 response to SHub get tile request is only attempted twice

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geotrellis-extensions#342]
A 429 response to a get tile request should be attempted 5 times before failing. According to [this test result](https://jenkins.vgt.vito.be/job/openEO/job/openeo-geotrellis-extensions/view/change-requests/job/PR-337/5/testReport/junit/org.openeo.extensions/PyramidFactoryTest/sentinelHubSmallAreaToTiff/), this is not the case:

> 29 Oct 10:12:28 WARN [geotrellissentinelhub.DefaultProcessApi] - Scheduled retry within PT1S because of 429 response in context: getTile sentinel-2-l2a 2022-09-19T00:00Z
29 Oct 10:12:29 ERROR [geotrellissentinelhub.DefaultProcessApi] - Not attempting to retry unrecoverable error in context: getTile sentinel-2-l2a 2022-09-19T00:00Z
org.openeo.geotrellissentinelhub.SentinelHubException: Sentinel Hub returned an error
response: HTTP/1.1 429 Too Many Requests with body: {"error":{"status":429,"reason":"Too Many Requests","message":"You have exceeded your rate limit","code":"RATE_LIMIT_EXCEEDED"}}

**Comment by EmileSonneveld** [comment]
Usually when I get this issue, it happens after running CI again. 
In [this example](https://jenkins.vgt.vito.be/job/openEO/job/openeo-geotrellis-extensions/job/develop/1227/testReport/junit/org.openeo.geotrellissentinelhub/PyramidFactoryTest/testSentinel2L2A/) the retry seems to work correctly till it fails
Maybe the retry is too fast, making the rate filing limit worse (I see: 1s, 1s, 2s, 2s, 2s, 4s, 5s, 6s, 8s).

**Comment by EmileSonneveld** [comment]
Maybe not relevant for this ticket, but other error that might need a retry:
```
net.jodah.failsafe.FailsafeException: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:385)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
	at org.openeo.geotrellissentinelhub.package$.withRetries(package.scala:58)
	at org.openeo.geotrellissentinelhub.DefaultCatalogApi.search(CatalogApi.scala:185)
```
https://jenkins.vgt.vito.be/job/openEO/job/openeo-geotrellis-extensions/view/change-requests/job/PR-337/12/testReport/junit/org.openeo.geotrellissentinelhub/PyramidFactoryTest/testSentinel5PL2DuplicateRequestsDatacube_seq/
