### ISSUE TITLE
support a larger number of geometries in SHub Catalog query

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geotrellis-extensions#93]
A user managed to overwhelm the SHub Catalog API with a query for >100000 polygons so that it started returning 503's and read timeouts:

```
net.jodah.failsafe.FailsafeException: java.net.SocketTimeoutException: Read timed out
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:385)
	at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:68)
	at org.openeo.geotrellissentinelhub.package$.withRetries(package.scala:59)
	at org.openeo.geotrellissentinelhub.DefaultCatalogApi.search(CatalogApi.scala:143)
	at org.openeo.geotrellissentinelhub.PyramidFactory.$anonfun$datacube_seq$8(PyramidFactory.scala:316)
	at org.openeo.geotrellissentinelhub.MemoizedCuratorCachedAccessTokenWithAuthApiFallbackAuthorizer.authorized(Authorizer.scala:76)
	at org.openeo.geotrellissentinelhub.PyramidFactory.authorized(PyramidFactory.scala:74)
	at org.openeo.geotrellissentinelhub.PyramidFactory.datacube_seq(PyramidFactory.scala:314)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at scalaj.http.HttpRequest.doConnection(Http.scala:367)
	at scalaj.http.HttpRequest.exec(Http.scala:343)
	at scalaj.http.HttpRequest.asString(Http.scala:492)
	at org.openeo.geotrellissentinelhub.DefaultCatalogApi.getFeatureCollectionPage$2(CatalogApi.scala:168)
	at org.openeo.geotrellissentinelhub.DefaultCatalogApi.getFeatures$1(CatalogApi.scala:177)
	at org.openeo.geotrellissentinelhub.DefaultCatalogApi.$anonfun$search$1(CatalogApi.scala:198)
	at org.openeo.geotrellissentinelhub.package$.$anonfun$withRetries$4(package.scala:59)
	at net.jodah.failsafe.Functions.lambda$get$0(Functions.java:46)
	at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:65)
	at net.jodah.failsafe.Execution.executeSync(Execution.java:128)
	at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:378)
	... 19 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1449)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1060)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:754)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at scalaj.http.HttpRequest.doConnection(Http.scala:365)
	... 29 more
```

In this case, the existing simplification was not adequate so we might want to extend it.

Possible solutions:

- spatially partitioning the polygons and sending separate API calls for each batch, then merge the features
- @jdries:

> we can probably use geotrellis 'clipToGrid' to convert those polygons into 256x256 tiles first, and then doing dissolve will also have more effect
> geotrellis cliptogrid will grid your polygons onto the same grid that we use for raster processing. So you get SpatialKey's. These keys can be converted to extents, which can be converted back to polygons.
Those polygons are then all simple squares, and a lot of them will be neighbouring. So doing an additional dissolve on that should result in a much simpler geometry compared to the original polygons.

**Comment by bossie** [comment]
Test case: https://github.com/Open-EO/openeo-geotrellis-extensions/blob/84741ec617755595577055137d402eb33fc4d85e/geotrellis-sentinelhub/src/test/scala/org/openeo/geotrellissentinelhub/DefaultCatalogApiTest.scala#L109-L136

**Comment by jdries** [comment]
@bossie  the 5k file can be found here:
https://artifactory.vgt.vito.be/webapp/#/artifacts/browse/simple/General/testdata-public/parcels/32TPT.geojson
With the fix, things seem to work fine again, can you maybe still add the test?

**Comment by bossie** [comment]
The fix was done in the PyramidFactory so I'll have to adapt the test.
