### ISSUE TITLE
exception with aggregate_temporal + aggregate_spatial

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#94]
Error reported by user with the script below.
My guess is that aggregate_temporal introduces empty MultibandTile objects, which aggregate_spatial doesn't deal with.

```
start_date = "2017-08-01"
end_date = "2018-04-28"

bands = ["B04", "B08", "SCL"]
con  = openeo.connect(https://openeo.vito.be/).authenticate_oidc(provider_id="egi")
dates = (start_date, end_date)


cube = con.load_collection("TERRASCOPE_S2_TOC_V2", temporal_extent=dates, bands=bands)

#define the masking kernel
g = scipy.signal.windows.gaussian(11, std=1.5)
kernel = np.outer(g, g)
kernel = kernel / kernel.sum()

 

classification = cube.band("SCL")
mask = ~ ((classification == 4) | (classification == 5))
mask = mask.apply_kernel(kernel)
mask = mask > 0.1

 

from openeo.extra.spectral_indices.spectral_indices import compute_index

ndvi = compute_index(cube, "NDVI")


maskedv2_ndvi = ndvi.mask(mask)
maskedv2_ndvi_dek = maskedv2_ndvi.aggregate_temporal_period(period = 'dekad', reducer = 'median')
maskedv2_timeseries_dek = maskedv2_ndvi_dek.aggregate_spatial(geometries=fields, reducer="mean")

 
job_options = {"executor-memory":"8G", "executor-memoryOverhead":"4G", "executor-cores":"2"}
cube = maskedv2_timeseries_dek.save_result(format="JSON")
job = cube.create_job(job_options=job_options)

job.start_job()

ava.lang.ArrayIndexOutOfBoundsException
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, TimestampType, fromJavaTimestamp, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, date), TimestampType), true, false) AS date#0
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 1, feature_index), IntegerType) AS feature_index#1
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 2, band_0), DoubleType) AS band_0#2
	at org.apache.spark.sql.errors.QueryExecutionErrors$.expressionEncodingError(QueryExecutionErrors.scala:1052)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:210)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:193)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doAggregateWithKeys_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

**Comment by JeroenVerstraelen** [comment]
https://github.com/Open-EO/openeo-geotrellis-extensions/commit/e3baea324dd8a707e36e28e1d8f6356d0104d385
https://github.com/Open-EO/openeo-geopyspark-driver/pull/270

**Comment by JeroenVerstraelen** [comment]
Adding a filterEmptyTile call before aggregate_spatial appears to be a good temporary solution.

This temporary fix has several issues:
- Aggregate_spatial should take into account NaN values
- It is infeasible to add an ad hoc solution for EmptyMultiBandTiles to every process

The reason the EmptyMultibandTile class was added to aggregate_temporal was because the number of bands is unknown inside the aggregate_temporal process. We can use the metadata.bandcount to derive this value, and then use ConstantTiles with NoData instead of EmptyMultibandTiles.

**Comment by JeroenVerstraelen** [comment]
We can't assume yet that org.openeo.geotrelliscommon.OpenEORasterCubeMetadata is available for every datacube. Although it should be somewhere in the future. This means that we can't remove the EmptyMultibandTile class entirely like the previous solution suggested.

For now we can attempt to properly set the bandcount field of EmptyMultiBandTiles when this OpenEORasterCubeMetadata is available. Then we can also edit aggregateSpatialForGeometry and aggregateSpatialForGeometryWithSpatialCube in org.openeo.geotrellis.aggregate_polygon.AggregatePolygonProcess to deal with EmptyMultiBandTiles where this field in unset.
