### ISSUE TITLE
batch process PU estimate: java.lang.ArithmeticException: Division by zero

### ISSUE THREAD

**Issue by bossie** [Open-EO/openeo-geotrellis-extensions#98]
Bumped into this one while trying to provoke Java DEBUG logging in the context of https://github.com/Open-EO/openeo-geopyspark-driver/issues/258:

Request:
```python
connection = openeo.connect("https://openeo-dev.vito.be").authenticate_oidc()

data_cube = (connection.load_collection("SENTINEL2_L2A_SENTINELHUB", bands=["B08", "B04", "B02", "SCL"])
             .filter_temporal(["2019-09-21", "2019-09-21"])
             .filter_bbox(west=471275.3098352262, south=5657503.248379398, east=492660.20213888795, north=5674436.759279663, crs="EPSG:32631"))

job = data_cube.execute_batch(out_format="GTiff", job_options={'sentinel-hub': {'input': 'batch'}})
```
Error:
```
Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/async_task.py", line 228, in main
    batch_jobs.poll_sentinelhub_batch_processes(job_info, sentinel_hub_client_alias, vault_token)
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 997, in poll_sentinelhub_batch_processes
    batch_processes = reduce(partial(dict_merge_recursive, overwrite=True),
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 998, in <genexpr>
    (batch_request_details(dependency) for dependency in dependencies))
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 993, in batch_request_details
    return {request_id: (batch_processing_service.get_batch_process(request_id),
  File "/opt/venv/lib64/python3.8/site-packages/openeogeotrellis/backend.py", line 993, in <dictcomp>
    return {request_id: (batch_processing_service.get_batch_process(request_id),
  File "/opt/venv/lib64/python3.8/site-packages/py4j/java_gateway.py", line 1321, in __call__
    return_value = get_return_value(
  File "/opt/venv/lib64/python3.8/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o0.get_batch_process.
: java.lang.ArithmeticException: Division by zero
	at java.base/java.math.BigDecimal.divide(BigDecimal.java:1774)
	at scala.math.BigDecimal.$div(BigDecimal.scala:555)
	at org.openeo.geotrellissentinelhub.BatchProcessingService.$anonfun$get_batch_process$4(BatchProcessingService.scala:170)
	at scala.Option.map(Option.scala:230)
	at org.openeo.geotrellissentinelhub.BatchProcessingService.$anonfun$get_batch_process$1(BatchProcessingService.scala:170)
	at org.openeo.geotrellissentinelhub.MemoizedCuratorCachedAccessTokenWithAuthApiFallbackAuthorizer.authorized(Authorizer.scala:76)
	at org.openeo.geotrellissentinelhub.BatchProcessingService.authorized(BatchProcessingService.scala:37)
	at org.openeo.geotrellissentinelhub.BatchProcessingService.get_batch_process(BatchProcessingService.scala:157)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Error can also be triggered by get_batch_process'ing the batch process generated by org.openeo.geotrellissentinelhub.BatchProcessingServiceTest#startBatchProcessForSentinel2: https://github.com/Open-EO/openeo-geotrellis-extensions/blob/1bc23d20fc621898d7d94ccd56e3f407f24b2988/geotrellis-sentinelhub/src/test/scala/org/openeo/geotrellissentinelhub/BatchProcessingServiceTest.scala#L86-L103

**Comment by bossie** [comment]
Awaiting the build of a new openeo-yarn image to include this fix in async_task on Nifi.

**Comment by bossie** [comment]
Works!
